[package]
name = "varlink-certification"
version = "2.0.1"
authors = ["Harald Hoyer <harald@redhat.com>"]
build = "build.rs"
edition = "2018"

[dependencies]
varlink = { version = "5", path = "../varlink" }
serde = "1"
serde_derive = "1"
serde_json = "1"
getopts = "0"
chainerror = "0.3"

[build-dependencies]
varlink_generator = { version = "6", path = "../varlink_generator" }

[dev-dependencies]
escargot = "0.3"
