[package]
name = "ping"
version = "2.0.0"
authors = ["Harald Hoyer <harald@redhat.com>"]
build = "build.rs"
edition = "2018"
publish = false

[dependencies]
varlink = { version = "10", path = "../../varlink" }
serde = "1.0.102"
serde_derive = "1.0.102"
serde_json = "1.0.41"
getopts = "0.2.21"
libc = "0.2.65"

[dev-dependencies]
chainerror = "0.4.2"

[build-dependencies]
varlink_generator = { version = "9", path = "../../varlink_generator" }
