[package]
name = "example"
version = "3.0.0"
authors = ["Harald Hoyer <harald@redhat.com>"]
edition = "2018"
publish = false

[dependencies]
varlink = { version = "10", path = "../../varlink" }
serde = "1.0.102"
serde_derive = "1.0.102"
serde_json = "1.0.41"
getopts = "0.2.21"
varlink_derive = { version = "9", path = "../../varlink_derive" }

chainerror = "0.4.3"
